name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_migrations:
        description: 'Run database migrations as part of deployment'
        required: true
        default: false
        type: boolean

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to production
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
          APP_PATH: ${{ secrets.APP_PATH }}
          RUN_MIGRATIONS: ${{ github.event.inputs.run_migrations || false }}
        run: |
          echo "Starting deployment to $SERVER_IP..."

          # Construct the deployment command
          DEPLOY_CMD="cd $APP_PATH && chmod +x deploy.sh && ./deploy.sh"
          if [ "$RUN_MIGRATIONS" = "true" ]; then
            DEPLOY_CMD="$DEPLOY_CMD --with-migrations"
          fi

          # Run the deployment script
          ssh $SSH_USER@$SERVER_IP "$DEPLOY_CMD"

          echo "Deployment completed successfully!"
